# Generated by Django 4.0.5 on 2022-07-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_teacherprofile_remove_teacher_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.AddField(
            model_name='user',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
