# Generated by Django 4.0.5 on 2022-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_teacherprofile_remove_teacher_courses_and_more'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('origin',)},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='topics',
            field=models.ManyToManyField(related_name='words', to='quizzes.topic'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
