# Generated by Django 4.0.5 on 2022-06-23 17:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_studentprofile_teacherprofile_remove_teacher_courses_and_more'),
        ('quizzes', '0002_alter_word_options_remove_topic_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutive_correct', models.PositiveSmallIntegerField(default=0)),
                ('times_seen', models.PositiveSmallIntegerField(default=0)),
                ('times_correct', models.PositiveSmallIntegerField(default=0)),
                ('next_review', models.DateField(default=datetime.date.today)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.AddField(
            model_name='topic',
            name='long_desc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='topic',
            name='short_desc',
            field=models.CharField(default='❓🧠❓', max_length=10),
        ),
        migrations.AddField(
            model_name='word',
            name='students',
            field=models.ManyToManyField(related_name='words', through='quizzes.WordScore', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wordscore',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.word'),
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('correct_answers', models.PositiveSmallIntegerField(default=0)),
                ('incorrect_answers', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.topic')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wordscore',
            unique_together={('word', 'student')},
        ),
    ]
