# Generated by Django 4.0.5 on 2022-06-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_wordscore_remove_topic_description_topic_long_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordscore',
            name='times_seen',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
