# Generated by Django 4.0.5 on 2022-07-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_remove_wordscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordscore',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
