# Generated by Django 4.0.5 on 2022-07-28 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_alter_topic_is_hidden_alter_topic_long_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='available_from',
            field=models.DateTimeField(default=datetime.date(2022, 7, 28)),
        ),
    ]
