# Generated by Django 4.0.5 on 2022-07-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_topic_available_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='available_from',
        ),
    ]
