# Generated by Django 4.0.5 on 2022-07-28 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_remove_topic_available_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='available_from',
            field=models.DateField(default=datetime.date(2022, 7, 29)),
        ),
    ]
