# Generated by Django 4.0.5 on 2022-07-29 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0012_topic_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='available_from',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
