# Generated by Django 4.0.5 on 2022-08-14 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0013_alter_topic_available_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
